### ISSUE TITLE
selected attribute not working

### ISSUE THREAD

**Issue by itajackass** [lcvriend/wc-multi-selector#1]
Hi, i tried to create a nested optgroups with this plugin.
But pre-selection with "selected" attribute on DOM load seems to not working.

    ...
    <option value="1" selected>TEST 1</option>
    ...

I'm expecting that TEST 1 is selected on load page, but nothing is selected...

**Comment by lcvriend** [comment]
Hi, thank you for your suggestion. Currently pre-selection is not possible. I agree, however, that it is basic functionality that should be supported both for loading from DOM and loading from JSON. I will have a look on how to implement this.

**Comment by itajackass** [comment]
Thankyou! Your plugin is very good and there no others one on web with same features: dropdown with infinite nested support + filter + multiselection!

**Comment by lcvriend** [comment]
In the [preselect-values branch](https://github.com/lcvriend/wc-multi-selector/tree/preselect-values) I have implemented this functionality. @itajackass: it would be really cool if you could test if it does what you expect it to do!

In the DOM it should work the way you have described:

```html
<multi-selector name="colors">
    <option>Red</option>
    <option>Yellow</option>
    <option selected>Green</option>
    <option selected>Blue</option>
</multi-selector>
```

In JSON you can preselect values like this:

```json
{
    "label": "Affirming the Consequent",
    "value": "Affirming the Consequent",
    "selected": true,
    "children": []
}
```

Note that when using JSON only items that do not themselves have children can be selected. For the container items the code will calculate if they should be (semi-)selected based on the selection state of their children.

**Comment by itajackass** [comment]
Perfect! It works like expected! Very nice now... i'm able to do not use ajax in my forms :)

**Comment by itajackass** [comment]
Hi another question: during form submit, values are always passed as JSON string like `["1","2","8"]`

So in my index.php page I need to manipulate data from multi-selector (convert from JSON to ARRAY) in a different way from other submitted traditional data:

      <?php
                 $json_id_from_multiselector = $_POST['ids'] ?? "";
                 $array_ids = $json_id_from_multiselector != "" ? json_decode($json_id_from_multiselector, true) : []; //<-- json to array
                 ...

Any change that during submit, data is already submitted as array? Thanks for your time
