### ISSUE TITLE
[Request info] Methods available

### ISSUE THREAD

**Issue by itajackass** [lcvriend/wc-multi-selector#2]
Hi, is there any methods to use?
For example i'd like to use this plugin in a search page: actually seems that search can be done only using ajax cause there is no way to preselect some "option" (option value="x" selected) on DOM/PAGE load.

So I ask if there is a method to use with jquery (on document ready) to set as "selected" some IDs from select to prevent using ajax.

Thanks

**Comment by lcvriend** [comment]
Hi, currently there is no method for selecting one or more values. I do think it could be useful to be able to manipulate the selection programmatically but I will have to think about the implementation. I suppose there should also be a method for removing one or more selected values. I will look into this!

**Comment by lcvriend** [comment]
I have added two methods in the [methods-for-changing-selection branch](https://github.com/lcvriend/wc-multi-selector/tree/methods-for-changing-selection):

- `addSelectedValues(...values)`
- `removeSelectedValues(...values)`

It should work similar to how the `add` and `remove` methods on the `classList` operate.

**Comment by itajackass** [comment]
Hi can write an example how it works the syntax using a standard button? thanks

    <button id="btn-addSelected">ADD SELECTED</button>

    $(document).ready(function() {
        $("#btn-addSelected").on("click", function(e) {
              e.preventDefault();
              var test_array_id = [1, 5, 7];
              ..... ?
        });
    });

**Comment by lcvriend** [comment]
I'm not all that familiar with jquery so here's a minimal vanilla js example:

```html
<html>
    <body>
        <multi-selector name="colors">
            <option>Red</option>
            <option>Yellow</option>
            <option>Green</option>
            <option>Blue</option>
        </multi-selector>
        <button id="changeValues">changeValues</button>
    </body>
    <script src="../src/wc-multi-selector.js"></script>
    <script>
        const ms = document.querySelector(`multi-selector`)
        document.getElementById("changeValues").addEventListener(
            "click",
            () => {
                const valuesToRemove = ["Green", "Blue"]
                ms.removeSelectedValues(...valuesToRemove)
                ms.addSelectedValues("Red", "Yellow")
            }
        )
    </script>
</html>
```

Looking at your example I'm assuming something like this should work:

```js
$(document).ready(function() {
    $("#btn-addSelected").on("click", function(e) {
          e.preventDefault();
          var test_array_id = [1, 5, 7];
          $("#my-multi-selector").addSelectedValues(...test_array_id);
    });
});
```

**Comment by itajackass** [comment]
Ok it seems jquery are not allowed (i get error: Uncaught TypeError: $(...).addSelectedValues is not a function)

But the code work with pure javascript:

     $(document).ready(function() {
         $("#btn-addSelected").on("click", function(e) {
              e.preventDefault();
              var test_array_id = [1, 5, 7];
              document.getElementById("my-multi-selector").addSelectedValues(test_array_id);
          });
      });
