### ISSUE TITLE
submit values as array instead of JSON string

### ISSUE THREAD

**Issue by lcvriend** [lcvriend/wc-multi-selector#4]
Hi another question: during form submit, values are always passed as JSON string like `["1","2","8"]`

So in my index.php page I need to manipulate data from multi-selector (convert from JSON to ARRAY) in a different way from other submitted traditional data:

```php
<?php
     $json_id_from_multiselector = $_POST['ids'] ?? "";
     $array_ids = $json_id_from_multiselector != "" ? json_decode($json_id_from_multiselector, true) : []; //<-- json to array
     ...
```

Any chance that during submit, data is already submitted as array? Thanks for your time

_Originally posted by @itajackass in https://github.com/lcvriend/wc-multi-selector/issues/1#issuecomment-1999119099_

**Comment by lcvriend** [comment]
The web component uses the [ElementInternals API](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/setFormValue) to set the submission value. As far as I know this is the standard way for sending formdata to a user agent.

I am unfamiliar with `php` but you could write a function in `javascript` that returns the selected values after clicking on a button. Would that work for your use case?

**Comment by itajackass** [comment]
Ok no problem. I'll manage the json to array conversion thanks
